[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci", "npm run prisma:generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run db:migrate:deploy && node apps/web/.next/standalone/apps/web/server.js"
